### ISSUE TITLE
Not working with MPI-Kepzig dataset

### ISSUE THREAD

**Issue by soichih** [brain-life/app-hcp-acpc-alignment#1]
When I run this App on MPI-Kepzig dataset, it generates completely misaligned output.

![screenshot from 2019-03-03 09-55-08](https://user-images.githubusercontent.com/923896/53696996-704f1680-3d9a-11e9-80e4-6fa1a7d7e94a.png)

robustfov seems to be working fine, but then flirt might be thrown off by the noise/face masking artifact for this dataset.. but I am not sure..

I wonder if we could/need to clean up the voxel outside the skull before passing it to flirt so that it can align it better with the template, but I am not sure how to do that. Suggestions welcomed!

**Comment by faskowit** [comment]
probably this issue can be closed now; it was indeed a problem of the noise of the mp2rage acquisition

**Comment by francopestilli** [comment]
@faskowit thanks for the feedback!
